# fly.toml app configuration file generated for quich on 2025-02-04T17:11:43Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'quich'
primary_region = 'otp'

[build]

[http_service]
  internal_port = 8888
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  max_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1