# fly.toml app configuration file generated for quich on 2025-02-04T17:11:43Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "quick-search"
build = { }
primary_region = "fra"

[http_service]
auto_start_machines = true
auto_stop_machines = true
force_https = true
internal_port = 8_888
min_machines_running = 0
processes = [ "app" ]

[[vm]]
cpu_kind = "shared"
cpus = 1
memory = "512mb"

[metrics]
  port = 8080
  path = "/metrics"
  app = "quich-search"