[tool.poetry]
name = "qui—Åh"
version = "0.1.0"
description = ""
authors = ["falcolnic <mykh.yano@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"
uvicorn = "^0.34.0"
sqlalchemy = "^2.0.36"
pydantic = "^2.10.3"
fastapi = "^0.115.6"
fasthx = "^2.1.1"
pyjwt = "^2.10.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
