"""add ideas

Revision ID: 4e5a572f649c
Revises: 91375a444acd
Create Date: 2025-02-14 22:16:37.274655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from models import custom_types


# revision identifiers, used by Alembic.
revision: str = '4e5a572f649c'
down_revision: Union[str, None] = '91375a444acd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ideas",
        sa.Column("id", custom_types.UUID_as_Integer(), nullable=False),
        sa.Column("idea", sa.String(), nullable=True),
        sa.Column("start", sa.Integer(), nullable=True),
        sa.Column("embedding", sa.BLOB(), nullable=True),
        sa.Column("video_id", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["video_id"],
            ["transcriptions.video_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("docs", schema=None) as batch_op:
        batch_op.drop_column("chunk_id")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("docs", schema=None) as batch_op:
        batch_op.add_column(sa.Column("chunk_id", sa.VARCHAR(), nullable=True))

    op.drop_table("ideas")
    # ### end Alembic commands ###