"""add status and error to transcriptions

Revision ID: 5844d490e443
Revises: b9a5b95c8e7a
Create Date: 2025-02-14 20:32:34.559561

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '5844d490e443'
down_revision: Union[str, None] = 'b9a5b95c8e7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("transcriptions", schema=None) as batch_op:
        batch_op.add_column(sa.Column("status", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("error", sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("transcriptions", schema=None) as batch_op:
        batch_op.drop_column("error")
        batch_op.drop_column("status")
    # ### end Alembic commands ###
