"""Create transcriptions, docs, and chunks tables

Revision ID: 691908104508
Revises: 96c5be368359
Create Date: 2025-02-12 23:53:54.290548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '691908104508'
down_revision: Union[str, None] = '96c5be368359'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "transcriptions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("transcript", sa.String(), nullable=False),
        sa.Column("video_id", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("video_id"),
    )
    op.create_table(
        "docs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("document", sa.String(), nullable=True),
        sa.Column("chunk", sa.String(), nullable=True),
        sa.Column("llm_chunk", sa.JSON(), nullable=True),
        sa.Column("start", sa.Integer(), nullable=True),
        sa.Column("duration", sa.Integer(), nullable=True),
        sa.Column("chunk_id", sa.String(), nullable=True),
        sa.Column("video_id", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["video_id"],
            ["transcriptions.video_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "chunks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("source", sa.String(), nullable=True),
        sa.Column("context", sa.String(), nullable=True),
        sa.Column("start", sa.Integer(), nullable=True),
        sa.Column("embedding", sa.BLOB(), nullable=True),
        sa.Column("chunk_id", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["chunk_id"],
            ["docs.chunk_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("chunks")
    op.drop_table("docs")
    op.drop_table("transcriptions")
    # ### end Alembic commands ###