"""add youtube table

Revision ID: 91375a444acd
Revises: 5844d490e443
Create Date: 2025-02-14 21:26:13.182732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from models import custom_types 

# revision identifiers, used by Alembic.
revision: str = '91375a444acd'
down_revision: Union[str, None] = '5844d490e443'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "youtube",
        sa.Column("id", custom_types.UUID_as_Integer(), nullable=False),
        sa.Column("video_id", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("author", sa.String(), nullable=True),
        sa.Column("publish_date", sa.DateTime(), nullable=True),
        sa.Column("channel_id", sa.String(), nullable=True),
        sa.Column("channel_url", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("video_id"),
    )
    with op.batch_alter_table("transcriptions", schema=None) as batch_op:
        batch_op.create_foreign_key(
            "youtube_id_transcriptions_foreign_key", "youtube", ["video_id"], ["video_id"]
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("transcriptions", schema=None) as batch_op:
        batch_op.drop_constraint("youtube_id_transcriptions_foreign_key", type_="foreignkey")

    op.drop_table("youtube")
    # ### end Alembic commands ###
