"""add youtube and idea table

Revision ID: 92323df3558f
Revises: 4e5a572f649c
Create Date: 2025-02-14 23:05:24.229459

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from models import custom_types

# revision identifiers, used by Alembic.
revision: str = "92323df3558f"
down_revision: Union[str, None] = "4e5a572f649c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "youtube",
        sa.Column("id", custom_types.UUID_as_Integer(), nullable=False),
        sa.Column("video_id", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("author", sa.String(), nullable=True),
        sa.Column("publish_date", sa.DateTime(), nullable=True),
        sa.Column("channel_id", sa.String(), nullable=True),
        sa.Column("channel_url", sa.String(), nullable=True),
        sa.Column("views", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("video_id"),
    )
    op.create_table(
        "ideas",
        sa.Column("id", custom_types.UUID_as_Integer(), nullable=False),
        sa.Column("idea", sa.String(), nullable=True),
        sa.Column("start", sa.Integer(), nullable=True),
        sa.Column("embedding", sa.BLOB(), nullable=True),
        sa.Column("kind", sa.String(), nullable=True),
        sa.Column("video_id", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["video_id"],
            ["youtube.video_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )

    with op.batch_alter_table("transcriptions", schema=None) as batch_op:
        batch_op.create_foreign_key(
            "transcriptions_video_id_foreign_key", "youtube", ["video_id"], ["video_id"]
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("transcriptions", schema=None) as batch_op:
        batch_op.drop_constraint("transcriptions_video_id_foreign_key", type_="foreignkey")

    with op.batch_alter_table("docs", schema=None) as batch_op:
        batch_op.add_column(sa.Column("chunk_id", sa.VARCHAR(), nullable=True))

    op.drop_table("ideas")
    op.drop_table("youtube")
    # ### end Alembic commands ###
