"""update transcription and docs tables

Revision ID: b9a5b95c8e7a
Revises: 691908104508
Create Date: 2025-02-13 13:55:57.276772

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from models import custom_types

# revision identifiers, used by Alembic.
revision: str = "b9a5b95c8e7a"
down_revision: Union[str, None] = "691908104508"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "transcriptions",
        sa.Column("id", custom_types.UUID_as_Integer(), nullable=False),
        sa.Column("transcript", sa.JSON(), nullable=False),
        sa.Column("video_id", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("video_id"),
    )
    op.create_table(
        "docs",
        sa.Column("id", custom_types.UUID_as_Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("source", sa.String(), nullable=True),
        sa.Column("source_json", sa.JSON(), nullable=True),
        sa.Column("llm_metadata", sa.JSON(), nullable=True),
        sa.Column("summary", sa.String(), nullable=True),
        sa.Column("start", sa.Integer(), nullable=True),
        sa.Column("duration", sa.Integer(), nullable=True),
        sa.Column("title_embedding", sa.BLOB(), nullable=True),
        sa.Column("summary_embedding", sa.BLOB(), nullable=True),
        sa.Column("source_embedding", sa.BLOB(), nullable=True),
        sa.Column("total_embedding", sa.BLOB(), nullable=True),
        sa.Column("chunk_id", sa.String(), nullable=True),
        sa.Column("video_id", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["video_id"],
            ["transcriptions.video_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("docs")
    op.drop_table("transcriptions")
    # ### end Alembic commands ###
