"""Initial migration

Revision ID: ee9bc13f3a5c
Revises: 
Create Date: 2025-02-08 15:26:31.983559

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ee9bc13f3a5c"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "chunks", "id", existing_type=sa.NUMERIC(), type_=sa.UUID(), existing_nullable=False
    )
    op.create_foreign_key(None, "chunks", "docs", ["chunk_id"], ["chunk_id"])
    op.alter_column(
        "docs", "id", existing_type=sa.NUMERIC(), type_=sa.UUID(), existing_nullable=False
    )
    op.create_foreign_key(None, "docs", "transcriptions", ["video_id"], ["video_id"])
    op.alter_column(
        "transcriptions", "id", existing_type=sa.NUMERIC(), type_=sa.UUID(), existing_nullable=False
    )
    op.alter_column(
        "videos", "id", existing_type=sa.NUMERIC(), type_=sa.UUID(), existing_nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "videos", "id", existing_type=sa.UUID(), type_=sa.NUMERIC(), existing_nullable=False
    )
    op.alter_column(
        "transcriptions", "id", existing_type=sa.UUID(), type_=sa.NUMERIC(), existing_nullable=False
    )
    op.drop_constraint(None, "docs", type_="foreignkey")
    op.alter_column(
        "docs", "id", existing_type=sa.UUID(), type_=sa.NUMERIC(), existing_nullable=False
    )
    op.drop_constraint(None, "chunks", type_="foreignkey")
    op.alter_column(
        "chunks", "id", existing_type=sa.UUID(), type_=sa.NUMERIC(), existing_nullable=False
    )
    # ### end Alembic commands ###
